### ISSUE TITLE
DataSet subjects - should it retun whole obj representation?

### ISSUE THREAD

**Issue by yonyonson** [webofdata/specification#4]
Hei!

It says in the spec:

```When a client uses this endpoint they receive a json array that contains the subject representations in the named dataset```

Does it means that the server return only the list of subjects (IDs) of objects in the dataset, or should it return the contents of the object from the perspective of the dataset? I presume that the whole contents of the object are delivered, but that would be nice to confirm.

Cheers and keep up work with the spec,
Petr

**Comment by gra-moore** [comment]
Glad you like the work. This is kind of unified Topic Maps / RDF / SDShare / Linked Data / JSON-LD / Linked Data Fragments / and Lightweight SPARUL for management. I hope to put out a reference impl soon.

To answer your question: Its the full representations inline. e.g. not like sdshare, but like sdshare inline. I will update the spec to be clearer.

**Comment by yonyonson** [comment]
Good, thank you!
